#!/usr/bin/env bash
# workflow-viz.sh
#
# Finds every NodejsFunction entry file referenced in the CDK stack(s),
# runs durable-viz against each one, and writes:
#   - workflow-viz/<name>.mermaid  (always)
#   - workflow-viz/<name>.png      (if @mermaid-js/mermaid-cli is installed)
#   - WORKFLOWS.md                 (documentation with diagrams + I/O types)
#
# Requirements:
#   - durable-viz  (npm install --save-dev durable-viz)
#   - mmdc         (optional, for PNG: npm install --save-dev @mermaid-js/mermaid-cli)
#
# Usage:
#   npm run workflow-viz

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/workflow-viz"
WORKFLOWS_MD="$REPO_ROOT/WORKFLOWS.md"
MMDC="$REPO_ROOT/node_modules/.bin/mmdc"
DURABLE_VIZ="$REPO_ROOT/node_modules/.bin/durable-viz"

mkdir -p "$OUT_DIR"

# ── Discover entry files ──────────────────────────────────────────────────────
ENTRIES_FILE="$(mktemp)"

for stack_file in $(find "$REPO_ROOT/lib" "$REPO_ROOT/bin" -name "*.ts" 2>/dev/null); do
  stack_dir="$(dirname "$stack_file")"

  while IFS= read -r line; do
    raw="${line#*entry:}"

    # Case 1: path.join(__dirname, 'seg1', 'seg2', ...) or path.resolve(...)
    if echo "$raw" | grep -qE 'path\.(join|resolve)\('; then
      segments=""
      while IFS= read -r seg; do
        [[ "$seg" == "__dirname"* ]] && continue
        segments="$segments/$seg"
      done < <(echo "$raw" | grep -oE "'[^']+'" | tr -d "'")

      if [[ -n "$segments" ]]; then
        candidate="$stack_dir$segments"
        candidate="$(cd "$(dirname "$candidate")" 2>/dev/null && pwd)/$(basename "$candidate")" || true
        if [[ -f "$candidate" ]]; then
          echo "$candidate" >> "$ENTRIES_FILE"
        fi
      fi

    # Case 2: plain quoted relative path  entry: '../lambda/index.ts'
    elif echo "$raw" | grep -qE "['\"][^'\"]+\.ts['\"]"; then
      rel="$(echo "$raw" | grep -oE "['\"][^'\"]+\.ts['\"]" | tr -d "'\"")"
      if [[ -n "$rel" ]]; then
        candidate="$(cd "$stack_dir" && realpath "$rel" 2>/dev/null)" || true
        if [[ -f "$candidate" ]]; then
          echo "$candidate" >> "$ENTRIES_FILE"
        fi
      fi
    fi
  done < <(grep -E 'entry\s*:' "$stack_file" 2>/dev/null)
done

ENTRIES_SORTED="$(sort -u "$ENTRIES_FILE")"
rm -f "$ENTRIES_FILE"

# Fallback: scan lambda* directories
if [[ -z "$ENTRIES_SORTED" ]]; then
  echo "[workflow-viz] No entry files found in stack source — scanning lambda dirs..."
  ENTRIES_SORTED="$(find "$REPO_ROOT" -maxdepth 3 \
    \( -path "*/node_modules" -o -path "*/cdk.out" -o -path "*/dist" \) -prune \
    -o -name "index.ts" -path "*/lambda*" -print \
    | sort -u)"
fi

if [[ -z "$ENTRIES_SORTED" ]]; then
  echo "[workflow-viz] No Lambda entry files found. Nothing to do."
  exit 0
fi

echo "[workflow-viz] Found entry file(s):"
echo "$ENTRIES_SORTED" | while IFS= read -r e; do echo "  $e"; done
echo ""

# ── Check durable-viz ─────────────────────────────────────────────────────────
if [[ ! -x "$DURABLE_VIZ" ]]; then
  echo "[workflow-viz] Error: durable-viz not found at $DURABLE_VIZ"
  echo "  Run: npm install --save-dev durable-viz"
  exit 1
fi

# ── Check mmdc (optional) ─────────────────────────────────────────────────────
HAS_MMDC=false
if [[ -x "$MMDC" ]]; then
  HAS_MMDC=true
else
  echo "[workflow-viz] mmdc not found — skipping PNG output."
  echo "  To enable PNG: npm install --save-dev @mermaid-js/mermaid-cli"
  echo ""
fi

# ── Helper: extract the input interface block from a TS file ──────────────────
extract_interface() {
  local file="$1"
  # Print all interface blocks found in the file
  awk '
    /^interface / { in_block=1; block=$0; next }
    in_block {
      block = block "\n" $0
      if (/^\}/) { print block; in_block=0; block="" }
    }
  ' "$file"
}

# ── Helper: extract the return type annotation or infer from return statement ──
extract_return() {
  local file="$1"
  # Look for explicit return type on the handler arrow, else grab last return obj
  grep -E 'async \(event.*\).*:' "$file" | head -1 | grep -oE ':\s*Promise<[^>]+>' | head -1 || true
}

# ── Generate diagrams + WORKFLOWS.md ─────────────────────────────────────────

# Start the markdown file
cat > "$WORKFLOWS_MD" << 'MDHEADER'
# Workflows

Auto-generated by `npm run workflow-viz`. Do not edit manually.

> Diagrams are produced by [durable-viz](https://github.com/gunnargrosch/durable-viz)
> via static analysis of the handler source — no deployment required.

---

MDHEADER

echo "$ENTRIES_SORTED" | while IFS= read -r entry; do
  name="$(basename "$(dirname "$entry")")"
  mermaid_file="$OUT_DIR/${name}.mermaid"
  png_file="$OUT_DIR/${name}.png"
  # Make path relative to repo root (macOS-compatible, no GNU realpath needed)
  rel_entry="${entry#$REPO_ROOT/}"

  echo "[workflow-viz] Processing: $entry"

  # Generate Mermaid source
  if "$DURABLE_VIZ" "$entry" > "$mermaid_file" 2>/tmp/durable-viz-err; then
    echo "  Written: workflow-viz/${name}.mermaid"
  else
    echo "  Error running durable-viz on $entry:"
    cat /tmp/durable-viz-err
    rm -f "$mermaid_file"
    continue
  fi

  # Generate PNG if mmdc is available
  PNG_WRITTEN=false
  if [[ "$HAS_MMDC" == true ]]; then
    if "$MMDC" -i "$mermaid_file" -o "$png_file" -b transparent 2>/tmp/mmdc-err; then
      echo "  Written: workflow-viz/${name}.png"
      PNG_WRITTEN=true
    else
      echo "  Warning: mmdc failed for ${name}:"
      cat /tmp/mmdc-err
    fi
  fi

  # ── Append section to WORKFLOWS.md ─────────────────────────────────────────
  # Derive a human-readable title from the directory name
  title="$(echo "$name" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')"

  {
    echo "## $title"
    echo ""
    echo "**Source:** \`$rel_entry\`"
    echo ""

    # Input types
    interfaces="$(extract_interface "$entry")"
    if [[ -n "$interfaces" ]]; then
      echo "### Input"
      echo ""
      echo '```typescript'
      echo "$interfaces"
      echo '```'
      echo ""
    fi

    # Return type (best-effort)
    ret="$(extract_return "$entry")"
    if [[ -n "$ret" ]]; then
      echo "### Output"
      echo ""
      echo '```typescript'
      echo "handler$ret"
      echo '```'
      echo ""
    fi

    # Embed diagram
    echo "### Diagram"
    echo ""

    if [[ "$PNG_WRITTEN" == true ]]; then
      echo "![${title} workflow](workflow-viz/${name}.png)"
      echo ""
    fi

    echo '```mermaid'
    cat "$mermaid_file"
    echo '```'
    echo ""
    echo "---"
    echo ""
  } >> "$WORKFLOWS_MD"

done

echo ""
echo "[workflow-viz] Written: WORKFLOWS.md"
echo "[workflow-viz] Done. Output in: workflow-viz/"
